manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
#    - name: petejohanson # <-- enable the drivers
#      url-base: https://github.com/petejohanson
  projects:
#    - name: cirque-input-module
#      remote: petejohanson
#      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
