manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll
      import: app/west.yml
    # replace the one above with the commented one below when it gets merged into zmk
    # must swap the zmk-fingerpunch-keyboards repo as well at the same time
    #- name: zmk
    #  remote: zmkfirmware
    #  revision: main
    #  import: app/west.yml
  self:
    path: config
